### ISSUE TITLE
Prevent with_mock from touching base R packages

### ISSUE THREAD

**Issue by hadley** [hadley/testthat#546]
As it breaks things with the byte code compiler (and it's just a bad idea in general)

**Comment by krlmlr** [comment]
Hm... Does trace() work with byte code?

**Comment by gaborcsardi** [comment]
@krlmlr I doubt it.

But nevertheless, if you want to `trace` to do the mocking, how do you force the mocked function to return? And if you manage to do that, how do you make sure that the mocked function falls back if it is called from the bytecode compiler or from a finalizer?

Technical difficulties aside, I agree with @hadley that it is a bad idea, and not just for base packages, but anything that your package under testing is not calling directly. And then we might as well use sg else instead of in-place mocking. Imo.

**Comment by krlmlr** [comment]
We could build or own version of trace() that works the way we need to. I've counted [~150 hits](https://github.com/search?q=org%3Acran+with_mock&type=Code) in CRAN packages, so we should at least provide an alternative. Original PR for reference: #160.

@sainathadapa @lbartnik @n-s-f: CC-ing you as the authors of stubthat and mockery.

**Comment by gaborcsardi** [comment]
@krlmlr It does not matter if we write our own `trace()`, because the fundamental problem cannot be solved: we cannot make the mocking temporary, and keep the original function for the byte compiler (or other R code).

Btw. 150 hits don't mean 150 packages, and this issue is about base packages only, anyway. So that could be only a handful of packages.

**Comment by n-s-f** [comment]
@krlmlr mockery avoids this issue by only mocking out functions in the environment of a single function, not globally. 

The user specifies first the function that will call the mocked out function, and second the name of the function to mock out. Then, broadly speaking, we get that specific first function to execute in a new environment where the second function is mocked out but everything else is the same.

I don't think that kind of solution is applicable in the context of `with_mock`. 

That said, if there's a way to recursively generate a list of functions called from within the `with_mock` call (and functions called from those functions, etc.) using static analysis, then behind the scenes you could just use something similar to mockery's `stub` function on all of those functions and get the same expected behavior as a normal `with_mock` call. It would be tricky to keep track of exactly what should go back into which environment, but it should be possible.

**Comment by hadley** [comment]
We simply have to break this because it's not going to work with the next version of R.  I think it might be best to deprecate (or soft deprecate) `with_mock` and encourage people to use alternative packages. (I think mocking in R is complex and opinionated enough to be worth its own package)

**Comment by lbartnik** [comment]
There's the `mockery` package which could take over `with_mock`.

**Comment by krlmlr** [comment]
I haven't tried yet, but it might be possible to just fix `with_mock()` so that it works with byte-compiled code, and at the same time soft-deprecate it and move it somewhere else.

**Comment by gaborcsardi** [comment]
As for as temporary fix, you can turn off the byte compiler in `with_mock`. @kalibera was not very happy with this as the "final" solution, but maybe it is OK as a temporary workaround, and `with_mock` can also give a warning. This would give people some time to update.

**Comment by krlmlr** [comment]
@gaborcsardi: What do you mean by "turning off the byte compiler in `with_mock()`"? I thought the failures come from testthat's inability to replace the functions that already have been compiled to bytecode in the base packages?

**Comment by gaborcsardi** [comment]
AFAIK the problem is that the byte compiler (which is implemented in R currently) calls the mocked function.

**Comment by krlmlr** [comment]
I can't see how to possibly fix `with_mock()`. I suspect that the byte compiler uses inlining, this means that there's no way to catch all occurrences:

```r
testthat::with_mock(`base::inherits` = function(...) stop("oops"), as.person("Some Body"))
## Calls stop("oops"), but from the wrong location -- a helper function instantiated (but not byte-compiled) in this function
```

@hadley: How about:

- Warn that `with_mock()` won't work in R >= 3.4.0 (or R >= 4.0?), but keep it functional for now (to simplify CRAN release)
- Forbid mocking anything but functions defined in the package under test

**Comment by krlmlr** [comment]
@hadley: I've tried with_mock() with current R-devel, and I saw problems probably related to the inlining performed by the byte compiler. What else breaks in R-devel? I'm asking because I'm not sure it's specific to base packages.

**Comment by gaborcsardi** [comment]
So this is fine? https://github.com/hadley/testthat/issues/543#issuecomment-259664452

**Comment by hadley** [comment]
I think mocking base packages is absolutely bad/impossible, and in general, I think mocking anything outside the current package is likely to fail, and I'm not even sure about mocking within the current package.

@kalibera can give more details.

**Comment by krlmlr** [comment]
I think we've sorted this out in #543 by now. I think mocking in the current package can be implemented reliably (with a shadow environment), but perhaps best outside testthat.

**Comment by n-s-f** [comment]
@krlmlr I'm not sure if you're aware of what [mockery](https://github.com/n-s-f/mockery) does, but it's effectively what you're suggesting. Using a a shadow environment makes it possible to mock out things from anywhere, including base packages & primitives, without encountering any of the problems listed in these threads. At the moment it can only mock things out from functions that are called directly from the test function, but I'm [working](https://github.com/n-s-f/mockery/issues/17) on removing that limitation.

**Comment by krlmlr** [comment]
@n-s-f Thanks for the heads up, I'll need to revisit your implementation. I was thinking about something stupid like:

```r
shadow_env <- new.env(parent = asNamespace(getPackage()))
for (func_name in namespace_funcs()) {
  func <- get_func(func_name)
  environment(func) <- shadow_env
  shadow_env[["func_name"]] <- func
}
update_shadow_env(shadow_env, mocks)
```

and then evaluating expressions in the shadow env (or even temporarily patching the search path). As far as I see, this would give you mocking with infinite depth right away, but I might me missing a point.

**Comment by n-s-f** [comment]
@krlmlr I see. If a user were making a database call like

```R
myconn <- RODBC::odbcConnect(...)
data <- RODBC::sqlQuery(...)
```

and that user didn't want to actually interact with the database, I'm not sure I understand how your approach would allow them to mock out the db calls.  My understanding is that namespaced function calls like that skip the search path.

**Comment by krlmlr** [comment]
That would require temporarily patching the search path, just like `devtools::load_all()` does.

**Comment by n-s-f** [comment]
Doesn't the `::` operator skip the search path and jump directly to the namespace of interest? Are you talking about swapping out the namespaces of the functions temporarily for the duration of the test? I considered that, but one of the things I think is nice about `stub` is it's written in such a way that there's no clean up, so you don't need to use a code block as with `with_mock`. I also don't like patching the search path because I _believe (but have not tested it) that if you run your tests in parallel the search path would be patched (and your shadow namespace would be loaded) for all workers while the test that mocks is running, which can cause problems for other tests that don't want that namespace mocked.

If you're interested, I can explain my approach in another thread.

**Comment by krlmlr** [comment]
Avoiding cleanup is nice, although I'm pretty sure that parallel workers are sufficiently isolated from each other to not affect each other's search path. In the very basic scenario, where I mock one of my functions and don't need to hande callbacks from other packages, my approach doesn't need any cleanup either. So, swapping out namespaces can be added as necessary, if at all.

One thing to consider is that we're using mocking here for our tests as well. If we used a function from a package that imports testthat, we'd need to suggest that package and lazy-load it. The easiest thing might be a separate package that specializes on this kind of task; that package could then also import pkgload which handles namespace tasks.

**Comment by krlmlr** [comment]
I have implemented a [drop-in replacement for `with_mock()`](https://github.com/krlmlr/mockr), most original tests pass.

- Uses a shadow environment that is temporarily inserted just before the evaluation environment in the environment chain.
    - Infinite depth, mocks can still access and update local variables
    - Cleanup is still necessary, because changing the parent environment is permanent.
- Callbacks from other packages are not handled yet.
- Need to document how the mocking works internally.

This reimplementation and stub() can well coexist, but I feel we need something that closer matches the original behavior.

**Comment by kalibera** [comment]
Please be aware that you cannot freely insert new environments. This is a problem that several packages that manipulate environments have run into, mostly unit-testing frameworks. Simplified a bit, the byte-code compiler requires that you first have local environments (all environments up to topenv), then namespace and namespace-imports environments, then globalenv, and then global environments (non-namespace). See e.g. compiler:::frameTypes for more details. Testing with these settings should reveal problems with insertion of invalid environments: R_COMPILER_SUPPRESS_ALL=false R_JIT_STRATEGY=4. The cleanest way to mock I think would be through code generation: you would modify the call sites of functions.

**Comment by krlmlr** [comment]
@kalibera: Thanks. I'm inserting a local environment between topenv and the parent frame -- a replica of the namespace environment. It's created by `new.env()` and not by a function call, though. Would that still be a problem for the byte compiler?

**Comment by kalibera** [comment]
Not sure from your description, but if you were inserting local environment inside other local environments, this particular check would be fine. "Fine" but you are doing low-level operations like replicating a namespace into something that looks like a namespace but isn't quite. And the other problems remain. I think mocking especially implemented this way is a bad thing. I could understand mocking via code modification (before the code is loaded) of the current package.
